### ISSUE TITLE
Non-executable files set with executable permissions

### ISSUE THREAD

**Issue by mensfeld** [FlavourSys/mxfinfo#2]
Hey there,

While reviewing the source code of `mxfinfo` I've noticed, that a file in the `spec/fixtures/` directory have executable permissions while not being an executables.

```
spec/fixtures/IMG_0395.MOV.A14DC7130D.mxf
```
is that something intended? If so, I would appreciate an explanation as I often find it as a bug.

Thank you :pray:

**Comment by mensfeld** [comment]
Also not sure if references like this: https://my.diffend.io/gems/mxfinfo/0.1.3/0.2.0#d2h-130397-616 will work for anyone else than you.

**Comment by bigzed** [comment]
Thanks.
